apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-deployer-aceflows-rolebinding
subjects:
  - kind: ServiceAccount
    name: pipeline-deployer-serviceaccount
    namespace: pipeline-ace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-deployer-aceflows-role
